#!/bin/bash
# librarian.sh - Updates the README with the latest agent-generated manuals
# Executed by the automated Manifesto worker service

README_FILE="README.md"
# Scanning the local Free_Samples folder where the samples live
MANUALS_DIR="."
MARKER_START="<!-- MANUALS START -->"
MARKER_END="<!-- MANUALS END -->"

echo "[LIBRARIAN] Scanning for new manifesto goods..."

# Generate the list of files
LIST=""
for file in "$MANUALS_DIR"/*.md; do
    # Skip the README itself
    if [[ $(basename "$file") == "README.md" ]]; then
        continue
    fi
    filename=$(basename "$file")
    # Clean up filename for display (e.g., manifesto_v1.md -> Manifesto V1)
    display_name=$(echo "$filename" | sed 's/_/ /g' | sed 's/.md//g' | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}1')
    LIST="$LIST"$'\n'"* [📂 $display_name]($filename)"
done

# Check if markers exist, if not, append them
if ! grep -q "$MARKER_START" "$README_FILE"; then
    echo -e "\n## 📚 Manifesto Manuals (Agent-Generated)\nThe following manuals are generated by our autonomous worker agent.\n$MARKER_START\n$MARKER_END\n---\n*Looking for the full-length technical deep dives? [Visit the Premium Library](#)*" >> "$README_FILE"
fi

# Use sed to replace the content between markers
sed -i "/$MARKER_START/,/$MARKER_END/{ /$MARKER_START/{p; r /dev/stdin
}; /$MARKER_END/p; d }" "$README_FILE" <<EOF
$LIST
EOF

# Update the timestamp in the README badge
CURRENT_TIME=$(date +"%Y--%m--%d_%H:%M")
sed -i "s/Last_Sync-.*-green/Last_Sync-$CURRENT_TIME-green/g" "$README_FILE"

# Optional: Generate a visual tree structure if the 'tree' command is available
if command -v tree &> /dev/null; then
    echo "\`\`\`text" > tree_output.tmp
    tree -L 1 -P "*.md" --prune --noreport >> tree_output.tmp 2>/dev/null
    echo "\`\`\`" >> tree_output.tmp
    # Append tree output below the list if a specific marker exists, or just log it
    echo "[LIBRARIAN] Visual tree snapshot generated."
    rm tree_output.tmp
fi

echo "[LIBRARIAN] README Library updated successfully."
